### PR TITLE
test: added tests for button

### PR DESCRIPTION
**Pull request by anuraghazra**

### CODE REVIEW

**Comment by navin-moorthy** [comment]
I thought of removing react-aria component & use them as hooks in UI if necessary.

No need to bloat them in our build 🤔

**Comment by anuraghazra** [comment]
Oh i see. so what about the interactions?

**Comment by navin-moorthy** [comment]
> Oh i see. so what about the interactions?

We can remove them aswell, what do you say?

We are just using their hook & creating a Reakit component out of it.
Since we are now more concerned about the bundle size, we can use them directly in the UI as hook when needed.
That's my thought.

**Comment by anuraghazra** [comment]
> > Oh i see. so what about the interactions?
> 
> We can remove them aswell, what do you say?
> 
> We are just using their hook & creating a Reakit component out of it.
> Since we are now more concerned about the bundle size, we can use them directly in the UI as hook when needed.
> That's my thought.

I'm on favor of this approach from the start.

**Comment by navin-moorthy** [comment]
> > > Oh i see. so what about the interactions?
> > 
> > 
> > We can remove them aswell, what do you say?
> > We are just using their hook & creating a Reakit component out of it.
> > Since we are now more concerned about the bundle size, we can use them directly in the UI as hook when needed.
> > That's my thought.
> 
> I'm on favor of this approach from the start.

I just thought we could leverage this from our library.
But now I understand that we keep things separate as much as possible.

**Comment by navin-moorthy** [comment]
I think you can close this PR and I appreciate your work on tests 👏

**Comment by anuraghazra** [comment]
Closing this since we will be removing buttons and interactions

**Pull request closed without merging**
